"""Initial database schema

Revision ID: 4eb501671577
Revises: 
Create Date: 2025-12-18 16:04:06.411353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb501671577'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('member_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('trc', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('division', sa.String(length=50), nullable=True),
    sa.Column('wtrl_team_id', sa.Integer(), nullable=True),
    sa.Column('jersey_name', sa.String(length=255), nullable=True),
    sa.Column('jersey_image', sa.String(length=255), nullable=True),
    sa.Column('recruiting', sa.Boolean(), nullable=True),
    sa.Column('is_dev', sa.Boolean(), nullable=True),
    sa.Column('competition_class', sa.String(length=50), nullable=True),
    sa.Column('competition_season', sa.String(length=10), nullable=True),
    sa.Column('competition_year', sa.Integer(), nullable=True),
    sa.Column('competition_round', sa.Integer(), nullable=True),
    sa.Column('competition_status', sa.String(length=50), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('members_remaining', sa.Integer(), nullable=True),
    sa.Column('captain_name', sa.String(length=255), nullable=True),
    sa.Column('captain_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('trc')
    )
    op.create_table('race_results_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=50), nullable=False),
    sa.Column('race', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('finp', sa.Integer(), nullable=True),
    sa.Column('pbp', sa.Integer(), nullable=True),
    sa.Column('totp', sa.Integer(), nullable=True),
    sa.Column('falp', sa.Integer(), nullable=True),
    sa.Column('ftsp', sa.Integer(), nullable=True),
    sa.Column('time_result', sa.String(length=50), nullable=True),
    sa.Column('distance_result', sa.String(length=50), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.trc'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('race_results_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_results_teams_race'), ['race'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_results_teams_team_id'), ['team_id'], unique=False)

    op.create_table('round_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.trc'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('round_standings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_standings_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_standings_team_id'), ['team_id'], unique=False)

    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('team_trc', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['team_trc'], ['teams.trc'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('wtrl_riders',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('team_trc', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('tmuid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('member_status', sa.String(length=50), nullable=True),
    sa.Column('signedup', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=5), nullable=True),
    sa.Column('zftp', sa.Float(), nullable=True),
    sa.Column('zftpw', sa.Float(), nullable=True),
    sa.Column('zmap', sa.Float(), nullable=True),
    sa.Column('zmapw', sa.Float(), nullable=True),
    sa.Column('riderpoints', sa.Integer(), nullable=True),
    sa.Column('teams', sa.Integer(), nullable=True),
    sa.Column('appearances_round', sa.Integer(), nullable=True),
    sa.Column('appearances_season', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_trc'], ['teams.trc'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wtrl_riders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wtrl_riders_profile_id'), ['profile_id'], unique=False)

    op.create_table('race_lineup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(length=50), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('wtrl_rider_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['wtrl_rider_id'], ['wtrl_riders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'wtrl_rider_id', name='_race_wtrl_rider_uc')
    )
    op.create_table('race_results_riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_team_result_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.String(length=100), nullable=False),
    sa.Column('finp', sa.Integer(), nullable=True),
    sa.Column('pbp', sa.Integer(), nullable=True),
    sa.Column('totp', sa.Integer(), nullable=True),
    sa.Column('falp', sa.Integer(), nullable=True),
    sa.Column('ftsp', sa.Integer(), nullable=True),
    sa.Column('time_result', sa.String(length=50), nullable=True),
    sa.Column('distance_result', sa.String(length=50), nullable=True),
    sa.Column('wkg', sa.Float(), nullable=True),
    sa.Column('watts', sa.Float(), nullable=True),
    sa.Column('gap', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race_team_result_id'], ['race_results_teams.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['wtrl_riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('race_results_riders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_results_riders_race_team_result_id'), ['race_team_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_results_riders_rider_id'), ['rider_id'], unique=False)

    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('world', sa.String(length=50), nullable=True),
    sa.Column('course', sa.String(length=255), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('powerups', sa.Text(), nullable=True),
    sa.Column('fal_segments', sa.Text(), nullable=True),
    sa.Column('fts_segments', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('segments', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('leadin_distance', sa.Float(), nullable=True),
    sa.Column('leadin_ascent', sa.Float(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('pace_type', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=5), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_races_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_race_date'), ['race_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_round_id'), ['round_id'], unique=False)

    op.create_table('wtrl_competitions',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wtrl_leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('competition_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['wtrl_competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wtrl_divisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['wtrl_leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wtrl_races',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['wtrl_divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wtrl_races')
    op.drop_table('wtrl_divisions')
    op.drop_table('wtrl_leagues')
    op.drop_table('wtrl_competitions')
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_races_round_id'))
        batch_op.drop_index(batch_op.f('ix_races_race_date'))
        batch_op.drop_index(batch_op.f('ix_races_category'))

    op.drop_table('races')
    with op.batch_alter_table('race_results_riders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_results_riders_rider_id'))
        batch_op.drop_index(batch_op.f('ix_race_results_riders_race_team_result_id'))

    op.drop_table('race_results_riders')
    op.drop_table('race_lineup')
    with op.batch_alter_table('wtrl_riders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wtrl_riders_profile_id'))

    op.drop_table('wtrl_riders')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('rounds')
    with op.batch_alter_table('round_standings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_standings_team_id'))
        batch_op.drop_index(batch_op.f('ix_round_standings_class_id'))

    op.drop_table('round_standings')
    with op.batch_alter_table('race_results_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_results_teams_team_id'))
        batch_op.drop_index(batch_op.f('ix_race_results_teams_race'))

    op.drop_table('race_results_teams')
    op.drop_table('teams')
    op.drop_table('seasons')
    op.drop_table('riders')
    # ### end Alembic commands ###
