"""Add RiderAvailability model

Revision ID: 570e992c1f3c
Revises: 4eb501671577
Create Date: 2025-12-19 16:59:08.183206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '570e992c1f3c'
down_revision = '4eb501671577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rider_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wtrl_rider_id', sa.String(length=100), nullable=False),
    sa.Column('availability_data', mysql.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wtrl_rider_id'], ['wtrl_riders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wtrl_rider_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('team_trc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_trc', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('users_ibfk_1'), 'teams', ['team_trc'], ['trc'])

    op.drop_table('rider_availability')
    # ### end Alembic commands ###
