"""Refactor RaceLineup model for WTRL_Rider relationship

Revision ID: b97369663677
Revises: b4fe0a28bf47
Create Date: 2025-12-12 17:00:24.819325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b97369663677'
down_revision: Union[str, Sequence[str], None] = 'b4fe0a28bf47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race_lineup', sa.Column('wtrl_rider_id', sa.String(length=100), nullable=False))
    op.drop_index(op.f('_race_rider_uc'), table_name='race_lineup')
    op.create_unique_constraint('_race_wtrl_rider_uc', 'race_lineup', ['race_id', 'wtrl_rider_id'])
    op.create_foreign_key(None, 'race_lineup', 'wtrl_riders', ['wtrl_rider_id'], ['id'])
    op.drop_column('race_lineup', 'team_trc')
    op.drop_column('race_lineup', 'rider_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race_lineup', sa.Column('rider_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('race_lineup', sa.Column('team_trc', mysql.VARCHAR(length=10), nullable=False))
    op.drop_constraint(None, 'race_lineup', type_='foreignkey')
    op.drop_constraint('_race_wtrl_rider_uc', 'race_lineup', type_='unique')
    op.create_index(op.f('_race_rider_uc'), 'race_lineup', ['race_id', 'rider_id'], unique=True)
    op.drop_column('race_lineup', 'wtrl_rider_id')
    # ### end Alembic commands ###
